export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: (token) => `/auth/reset-password/${token}`,
    VALIDATE_RESET_TOKEN: (token) => `/auth/reset-password/${token}/validate`,
    ME: '/auth/me',
    TOKEN: '/auth/token',
    UPDATE_PROFILE: '/auth/me',
    DELETE_ACCOUNT: '/auth/me',
    EXPERIENCE: '/auth/me/experience',
    EDUCATION: '/auth/me/education',
    SKILLS: '/auth/me/skills',
    PROFILE_PHOTO: '/auth/me/photo/profile',
    BANNER_PHOTO: '/auth/me/photo/banner',
  },
  USERS: {
    ALL: '/users',
    SEARCH_USERS: '/users/search',
    BY_ID: (id) => `/users/${id}`,
  },
  CONNECTIONS: {
    REQUEST: (recipientId) => `/connections/request/${recipientId}`,
    ACCEPT: (requestId) => `/connections/accept/${requestId}`,
    REJECT: (requestId) => `/connections/reject/${requestId}`,
    REMOVE: (connectionId) => `/connections/${connectionId}`,
    STATUS: (otherUserId) => `/connections/status/${otherUserId}`,
    MY: '/connections/my',
    REQUESTS: '/connections/requests',
    MUTUAL: (otherUserId) => `/connections/mutual/${otherUserId}`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    READ_ALL: '/notifications/read-all',
    READ_ONE: (id) => `/notifications/${id}/read`,
  },
  JOBS: {
    BASE: '/jobs',
    MY_POSTS: '/jobs/my-posts',
    SAVED: '/jobs/saved',
    MY_APPLICATIONS: '/jobs/my-applications',
    BY_ID: (id) => `/jobs/${id}`,
    CLOSE: (id) => `/jobs/${id}/close`,
    SAVE: (id) => `/jobs/${id}/save`,
    APPLY: (id) => `/jobs/${id}/apply`,
    APPLICANTS: (id) => `/jobs/${id}/applicants`,
    APPLICATION_STATUS: (id, applicationId) => `/jobs/${id}/applicants/${applicationId}`,
  },
  MESSAGES: {
    CONVERSATIONS: '/messages/conversations',
    ARCHIVED: '/messages/conversations/archived',
    CONVERSATION: (id) => `/messages/conversations/${id}`,
    SEND_MESSAGE: (id) => `/messages/conversations/${id}/message`,
    READ: (id) => `/messages/conversations/${id}/read`,
    ARCHIVE: (id) => `/messages/conversations/${id}/archive`,
    CONNECTION_REQUEST: (id) => `/messages/conversations/${id}/connection-request`,
    BLOCK: (userId) => `/messages/block/${userId}`,
    UNBLOCK: (userId) => `/messages/unblock/${userId}`,
    BLOCKED: '/messages/blocked',
  },
};
