export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: (token) => `/auth/reset-password/${token}`,
    VALIDATE_RESET_TOKEN: (token) => `/auth/reset-password/${token}/validate`,
    ME: '/auth/me',
    UPDATE_PROFILE: '/auth/me',
    EXPERIENCE: '/auth/me/experience',
    EDUCATION: '/auth/me/education',
    SKILLS: '/auth/me/skills',
    PROFILE_PHOTO: '/auth/me/photo/profile',
    BANNER_PHOTO: '/auth/me/photo/banner',
  },
  USERS: {
    ALL: '/users',
    SEARCH_USERS: '/users/search',
    BY_ID: (id) => `/users/${id}`,
  },
  CONNECTIONS: {
    REQUEST: (recipientId) => `/connections/request/${recipientId}`,
    ACCEPT: (requestId) => `/connections/accept/${requestId}`,
    REJECT: (requestId) => `/connections/reject/${requestId}`,
    REMOVE: (connectionId) => `/connections/${connectionId}`,
    STATUS: (otherUserId) => `/connections/status/${otherUserId}`,
    MY: '/connections/my',
    REQUESTS: '/connections/requests',
    MUTUAL: (otherUserId) => `/connections/mutual/${otherUserId}`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    READ_ALL: '/notifications/read-all',
    READ_ONE: (id) => `/notifications/${id}/read`,
  },
};
